### ISSUE TITLE
Странный баг с АкибаБэкапом

### ISSUE THREAD

**Issue by kernusr** [JPathRu/attributes#10]
При переносе сайта акибой, почему то очищаются значения, в поле, типа textarea
Обычные текстовые поля - на месте, а вот многострочные - пустые

**Comment by AlekVolsk** [comment]
На актуальной версии Joomla и ackeeba backup проблема не выявлена, опишите конкретнее ваши условия воспроизведения: для чего атрибут, какого типа, что в значениях.

**Comment by kernusr** [comment]
Атрибут для ссылок на соцсети
Атрибут системный
Тип - многострочный текст

Контент вбит следующий:
`https://www.instagram.com/;instagram
https://www.youtube.com/;youtube`

Упаковывал акибой, в стандартной настройке. Пробовал упаковать/распаковать на:

- Локальный сервер под виндой OpenServer
- Боевой VPS на CentOS
- Шаред от никру (Ubuntu)
Результат всегда один и тотже - данное поле, после распаковки, пустое

**Comment by AlekVolsk** [comment]
Это баг самой акибы, что видно из её инсталлера:
`/installation/platform/models/joomlaconfiguration.php`,
`/installation/platform/models/joomlasetup.php`.
Акиба не восстанавливает файл конфигурации из архива как есть, исправляя только необходимые параметры, а перезаписывает файл с нуля, при этом многострочные параметры из исходного файла считываются некорректно: при экранировании спецсимволов, в т.ч. символов переносов строк что-то идёт не так и параметр теряет своё значение.

При этом внутри бекапа значение внутри *configuration.php* сохраняется.

За сохранение значения системного атрибута отвечает JConfig, вмешаться в работу которого практически малореально. Выход только один: не рекомендуется использовать многострочный тип параметров для системных атрибутов либо после восстановления из бекапа вручную из *configuration.php* бекапа выдёргивать значения многострочных параметров.
