### ISSUE TITLE
Куда пропал выбор layout?

### ISSUE THREAD

**Issue by kernusr** [JPathRu/attributes#11]
Было
![изображение](https://user-images.githubusercontent.com/16020878/126086809-8ed183f5-1aed-453e-9ccc-df16f90c5ca3.png)

Стало
![изображение](https://user-images.githubusercontent.com/16020878/126086820-d216a0a6-4caa-479e-95b7-f6bbec11164b.png)

**Comment by b2z** [comment]
@AlekVolsk может ты случайно удалил в 1.3.2.
https://github.com/JPathRu/attributes/commit/a5c1a97a3e2ea7f64c128f62ab1e5975f90505b5#diff-984fec7fcaced05a375f72bbb4f7fd05f9e1cf4265bd664799e979b2bb9ab940L70

**Comment by AlekVolsk** [comment]
Fixed in v1.3.3
