### ISSUE TITLE
Добавить шаблоны вывода

### ISSUE THREAD

**Issue by kernusr** [JPathRu/attributes#9]
Добавить ещё один параметр - шаблон вывода значения поля. Сами шаблоны можно оформить, как это сделано в modules.php. По файлу, на каждый тип поля, а в нём - каждая функция - описание нового представления. Либо, просто дёргать файл, с названием шаблона. Но, главное, чтобы была возможность наплодить шаблонов, сколько душе захочется.
По применению:
Например, я вывожу ссылки на соц сети плагином. Чтобы не писать один и тот же код несколько раз, было бы удобно создать шаблон вывода и просто вызывать атрибут, указав нужный шаблон.
Примеров применения много. Например, ещё я вывожу плагином телефоны и адреса электронной почты.

**Comment by AlekVolsk** [comment]
Реализовано в [v1.3.0](https://github.com/JPathRu/attributes/releases/tag/1.3.0)
